version: "3"

services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - D:\Project\php:/var/www/html/:delegated
      - ./conf.d/nginx/sites:/etc/nginx/conf.d/:delegated
      - ./logs/nginx:/var/log/nginx/:delegated
    environment:
      TZ: "Asia/Shanghai"

  php:
    build:
      context: ./build/php
      args:
        PHP_VERSION: "7.1"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - D:\Project\php:/var/www/html/:delegated
      - ./conf.d/php:/usr/local/etc/php/:delegated
    environment:
      TZ: "Asia/Shanghai"

  hyperf:
    build:
      context: ./build/hyperf
      args:
        PHP_VERSION: "7.3"
        ALPINE_VERSION: "3.11"
        SWOOLE_VERSION: "v4.5.7"
    ports:
      - "9501:9501"
    volumes:
      - D:\Project\hyperf:/hyperf/:delegated
      - ./conf.d/hyperf/php:/usr/local/etc/php/:delegated
    environment:
      TZ: "Asia/Shanghai"
    tty: true
    

  mysql:
    build:
      context: ./build/mysql
      args:
        MYSQL_VERSION: "8"
    ports:
      - "3306:3306"
      - "7001:7001"
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
      TZ: "Asia/Shanghai"
    volumes:
      - ./conf.d/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:delegated
      - ./data/mysql:/var/lib/mysql/:delegated
  
  go:
    build:
      context: ./build/go
      args:
        GO_VERSION: "1.15.11"
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - D:\Project\go:/go/:delegated
    tty: true


  pgsql:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1111"
      TZ: "Asia/Shanghai"
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data/:delegated
  #    - ./conf.d/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:delegated

  redis:
      image: redis:5
      ports:
        - "6379:6379"
      environment:
        #POSTGRES_PASSWORD: "1111"
        TZ: "Asia/Shanghai"
  
  # elasticsearch:
  #   image: elasticsearch:6.8.1
  #   container_name: es_search
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     TZ: "Asia/Shanghai"
  #   volumes:
  #     - ./data/elasticsearch:/usr/share/elasticsearch/data/:delegated

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.1/16
